pipeline {
	agent any
	tools {
		maven "maven-3.9.8"
	}
	stages {
        stage('Build') { 
            steps { 
                echo 'Build'
				sh "mvn clean verify"
            }
        }
        stage('Test'){
            steps {
                echo 'Test' 
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploy' 
            }
        }
    }
}